### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by smokez129** [imhunterand/CS2VSS#4]
![Skärmklipp](https://github.com/imhunterand/CS2VSS/assets/96570213/b9e499b2-bcfe-4d7b-89df-c67b9fc15e4c)
![image](https://github.com/imhunterand/CS2VSS/assets/96570213/3dcfa441-03b4-4931-a06a-56d0d9cc7688)

**Comment by imhunterand** [comment]
do you please screenshots the full image don't use a `crop` image for make a proof on concepts

**Comment by smokez129** [comment]
there you go
![image](https://github.com/imhunterand/CS2VSS/assets/96570213/b6cfc197-4fe3-475a-8f60-368782cba87f)
![image](https://github.com/imhunterand/CS2VSS/assets/96570213/efb6505c-82ca-4357-916d-5ec7cd3e63e2)

**Comment by smokez129** [comment]
theres some more errors but thats because of the missing files

**Comment by imhunterand** [comment]
no such file or directory , your folder can't read the files. where the files?

after i check this repositories i have no problem. deleted your files and downloaded again
